- name: Install or upgrade SigNoz k8s-infra
  hosts: k8s_control
  become: yes
  vars:
    release_name: "{{ release_name | default('k8s-infra') }}"
    namespace: "{{ namespace | default('signoz-infra') }}"
    cluster_name: "{{ cluster_name | default('vsphere-k8s') }}"
    deployment_environment: "{{ deployment_environment | default('dev') }}"
    signoz_otlp_endpoint: "{{ signoz_otlp_endpoint | default('10.172.27.3:4317') }}"
    signoz_otlp_insecure: "{{ signoz_otlp_insecure | default(true) }}"
  tasks:
    - name: Ensure Helm repo present/updated
      ansible.builtin.shell: |
        helm repo add signoz https://charts.signoz.io >/dev/null 2>&1 || true
        helm repo update
      args: { executable: /bin/bash }

    - name: Create namespace (idempotent)
      ansible.builtin.shell: "kubectl create ns {{ namespace }} --dry-run=client -o yaml | kubectl apply -f -"
      args: { executable: /bin/bash }

    - name: Render override values
      ansible.builtin.template:
        src: values-k8s-infra.yaml.j2
        dest: /tmp/values-k8s-infra.yaml
        mode: '0644'

    - name: Install/Upgrade k8s-infra
      ansible.builtin.shell: |
        helm upgrade --install {{ release_name }} signoz/k8s-infra \
          -n {{ namespace }} --create-namespace \
          -f /tmp/values-k8s-infra.yaml
      args: { executable: /bin/bash }

    - name: Show pods
      ansible.builtin.shell: "kubectl get pods -n {{ namespace }}"
      args: { executable: /bin/bash }
      register: pods_out
    - ansible.builtin.debug:
        var: pods_out.stdout_lines
