---
- hosts: k8s
  become: yes
  gather_facts: no

  vars_files:
    - group_vars/k8s.yml

  tasks:
    - name: Remove rolldice demo (ignore if missing)
      shell: |
        kubectl delete -f /opt/signoz/rolldice.yaml --ignore-not-found=true || true
        kubectl delete ns {{ apps_namespace }} --ignore-not-found=true || true
      args:
        executable: /bin/bash

    - name: Uninstall k8s-infra Helm release (ignore if missing)
      shell: |
        helm uninstall {{ release_name }} -n {{ signoz_namespace }} || true
      args:
        executable: /bin/bash

    - name: Delete namespace (ignore if in use)
      shell: |
        kubectl delete ns {{ signoz_namespace }} --ignore-not-found=true || true
      args:
        executable: /bin/bash

    - name: Clean working dir
      file:
        path: /opt/signoz
        state: absent
