---
- name: Install/upgrade k8s-infra and deploy rolldice
  hosts: local
  gather_facts: false

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Ensure target namespaces exist
      ansible.builtin.shell: |
        set -e
        kubectl get ns {{ ns }} >/dev/null 2>&1 || kubectl create ns {{ ns }}
        kubectl get ns {{ app_ns }} >/dev/null 2>&1 || kubectl create ns {{ app_ns }}
      args:
        executable: /bin/bash

    - name: Add/Update SigNoz Helm repo
      ansible.builtin.shell: |
        set -e
        helm repo add signoz https://charts.signoz.io >/dev/null 2>&1 || true
        helm repo update
      args:
        executable: /bin/bash

    - name: Render Helm override values from template
      ansible.builtin.template:
        src: ../helm-values/k8s-infra.values.yaml.j2
        dest: /tmp/k8s-infra.values.yaml
        mode: "0644"

    - name: Install/Upgrade k8s-infra chart
      ansible.builtin.shell: |
        set -e
        helm upgrade --install {{ release_name }} signoz/k8s-infra               --namespace {{ ns }}               --create-namespace               -f /tmp/k8s-infra.values.yaml               --wait
      args:
        executable: /bin/bash

    - name: Deploy rolldice app (optional)
      when: deploy_rolldice | bool
      ansible.builtin.shell: |
        set -e
        kubectl apply -n {{ app_ns }} -f ../k8s/rolldice/
      args:
        executable: /bin/bash

    - name: Show status (pods)
      ansible.builtin.shell: |
        echo "=== k8s-infra pods in namespace {{ ns }} ==="
        kubectl get pods -n {{ ns }} -o wide
        echo ""
        echo "=== rolldice pods in namespace {{ app_ns }} ==="
        kubectl get pods -n {{ app_ns }} -o wide || true
      args:
        executable: /bin/bash
